server:
  port: 7010

spring:
  application:
    name: mall-center
  datasource:
    url: jdbc:mysql://${zlt.datasource.ip}:3306/central_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${zlt.datasource.username}
    password: ${zlt.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:16379}
    timeout: 5000
    password: ${REDIS_PASSWORD:}
    database: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.central.mall.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# 商城配置
mall:
  goods:
    default-page-size: 20
    max-page-size: 100

# 多租户配置
zlt:
  tenant:
    enable: true
  # 数据权限
  datascope:
    enabled: false