-- =============================================
-- 盈亏平衡分析系统数据库表结构
-- 创建时间: 2024-01-15
-- 说明: 包含主分析表、场景表、敏感性分析表、预测表、配置表
-- =============================================

-- 1. 盈亏平衡分析主表
DROP TABLE IF EXISTS `soo_breakeven_analysis`;
CREATE TABLE `soo_breakeven_analysis` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `analysis_id` varchar(64) NOT NULL COMMENT '分析任务ID',
  `analysis_name` varchar(200) NOT NULL COMMENT '分析名称',
  `analysis_type` varchar(32) NOT NULL COMMENT '分析类型(monthly/quarterly/yearly)',
  `analysis_period` varchar(32) NOT NULL COMMENT '分析期间',
  `tenant_id` varchar(32) NOT NULL DEFAULT 'default' COMMENT '租户ID',
  `creator_id` bigint NOT NULL COMMENT '创建人ID',
  `creator_name` varchar(100) DEFAULT NULL COMMENT '创建人姓名',
  `current_parameters` longtext COMMENT '当前参数快照(JSON)',
  `breakeven_point` decimal(15,2) DEFAULT NULL COMMENT '盈亏平衡点',
  `total_fixed_cost` decimal(15,2) DEFAULT NULL COMMENT '总固定成本',
  `variable_cost_ratio` decimal(8,4) DEFAULT NULL COMMENT '变动成本率',
  `margin_safety` decimal(15,2) DEFAULT NULL COMMENT '安全边际',
  `margin_safety_ratio` decimal(8,4) DEFAULT NULL COMMENT '安全边际率',
  `scenario_results` longtext COMMENT '场景分析结果(JSON)',
  `sensitivity_data` longtext COMMENT '敏感性分析数据(JSON)',
  `forecast_results` longtext COMMENT '预测结果(JSON)',
  `reasonability_score` decimal(3,2) DEFAULT NULL COMMENT '合理性评分(0-1)',
  `constraint_violations` longtext COMMENT '约束违反记录(JSON)',
  `adjustment_history` longtext COMMENT '自动调整历史(JSON)',
  `calculation_trigger` varchar(32) DEFAULT NULL COMMENT '计算触发原因',
  `calculation_duration` int DEFAULT NULL COMMENT '计算耗时(毫秒)',
  `calculation_engine_version` varchar(32) DEFAULT NULL COMMENT '计算引擎版本',
  `last_recalculation` datetime DEFAULT NULL COMMENT '最后重算时间',
  `forecast_model` varchar(64) DEFAULT NULL COMMENT '使用的预测模型',
  `forecast_confidence` decimal(3,2) DEFAULT NULL COMMENT '预测置信度',
  `seasonal_factors` longtext COMMENT '季节性因子(JSON)',
  `model_metadata` longtext COMMENT '模型元数据(JSON)',
  `status` varchar(32) NOT NULL DEFAULT 'active' COMMENT '状态(active/archived/draft)',
  `is_real_time` tinyint(1) DEFAULT '0' COMMENT '是否实时计算',
  `auto_recalculation` tinyint(1) DEFAULT '1' COMMENT '是否自动重算',
  `alert_settings` longtext COMMENT '告警设置(JSON)',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int DEFAULT '1' COMMENT '版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_analysis_id_tenant` (`analysis_id`, `tenant_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_creator_id` (`creator_id`),
  KEY `idx_analysis_type` (`analysis_type`),
  KEY `idx_analysis_period` (`analysis_period`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_auto_recalculation` (`auto_recalculation`, `last_recalculation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='盈亏平衡分析主表';

-- 2. 盈亏平衡场景表
DROP TABLE IF EXISTS `soo_breakeven_scenarios`;
CREATE TABLE `soo_breakeven_scenarios` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `scenario_id` varchar(64) NOT NULL COMMENT '场景ID',
  `analysis_id` varchar(64) NOT NULL COMMENT '关联分析ID',
  `tenant_id` varchar(32) NOT NULL DEFAULT 'default' COMMENT '租户ID',
  `scenario_name` varchar(200) NOT NULL COMMENT '场景名称',
  `scenario_type` varchar(32) NOT NULL COMMENT '场景类型(conservative/baseline/optimistic/industry_specific)',
  `scenario_description` text COMMENT '场景描述',
  `is_baseline` tinyint(1) DEFAULT '0' COMMENT '是否基准场景',
  `is_recommended` tinyint(1) DEFAULT '0' COMMENT '是否推荐场景',
  `scenario_parameters` longtext COMMENT '场景参数配置(JSON)',
  `parameter_changes` longtext COMMENT '相对基准的参数变化(JSON)',
  `breakeven_point` decimal(15,2) DEFAULT NULL COMMENT '盈亏平衡点',
  `total_fixed_cost` decimal(15,2) DEFAULT NULL COMMENT '总固定成本',
  `variable_cost_ratio` decimal(8,4) DEFAULT NULL COMMENT '变动成本率',
  `margin_safety` decimal(15,2) DEFAULT NULL COMMENT '安全边际',
  `margin_safety_ratio` decimal(8,4) DEFAULT NULL COMMENT '安全边际率',
  `feasibility_score` decimal(3,2) DEFAULT NULL COMMENT '可行性评分',
  `risk_level` varchar(32) DEFAULT NULL COMMENT '风险等级(low/medium/high)',
  `confidence_level` decimal(3,2) DEFAULT NULL COMMENT '置信水平',
  `sensitivity_score` decimal(3,2) DEFAULT NULL COMMENT '敏感性评分',
  `revenue_impact` decimal(15,2) DEFAULT NULL COMMENT '营收影响',
  `cost_impact` decimal(15,2) DEFAULT NULL COMMENT '成本影响',
  `profit_impact` decimal(15,2) DEFAULT NULL COMMENT '利润影响',
  `implementation_cost` decimal(15,2) DEFAULT NULL COMMENT '实施成本',
  `payback_period` int DEFAULT NULL COMMENT '回收期(月)',
  `key_metrics` longtext COMMENT '关键指标(JSON)',
  `performance_indicators` longtext COMMENT '绩效指标(JSON)',
  `success_criteria` longtext COMMENT '成功标准(JSON)',
  `sort_order` int DEFAULT '0' COMMENT '排序序号',
  `status` varchar(32) NOT NULL DEFAULT 'active' COMMENT '状态',
  `last_calculated` datetime DEFAULT NULL COMMENT '最后计算时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scenario_id_tenant` (`scenario_id`, `tenant_id`),
  KEY `idx_analysis_id` (`analysis_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_scenario_type` (`scenario_type`),
  KEY `idx_is_baseline` (`is_baseline`),
  KEY `idx_is_recommended` (`is_recommended`),
  KEY `idx_sort_order` (`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='盈亏平衡场景表';

-- 3. 盈亏平衡敏感性分析表
DROP TABLE IF EXISTS `soo_breakeven_sensitivity`;
CREATE TABLE `soo_breakeven_sensitivity` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `analysis_id` varchar(64) NOT NULL COMMENT '关联分析ID',
  `tenant_id` varchar(32) NOT NULL DEFAULT 'default' COMMENT '租户ID',
  `parameter_name` varchar(100) NOT NULL COMMENT '敏感性参数名称',
  `parameter_label` varchar(200) DEFAULT NULL COMMENT '参数中文名称',
  `parameter_category` varchar(64) DEFAULT NULL COMMENT '参数类别(revenue/cost/price/volume/efficiency)',
  `baseline_value` decimal(15,4) DEFAULT NULL COMMENT '基准值',
  `variation_range` longtext COMMENT '变化范围(JSON数组)',
  `sensitivity_coefficient` decimal(10,6) DEFAULT NULL COMMENT '敏感度系数',
  `sensitivity_level` varchar(32) DEFAULT NULL COMMENT '敏感度等级(high/medium/low)',
  `elasticity_coefficient` decimal(10,6) DEFAULT NULL COMMENT '弹性系数',
  `impact_direction` varchar(32) DEFAULT NULL COMMENT '影响方向(positive/negative/neutral)',
  `impact_magnitude` decimal(10,4) DEFAULT NULL COMMENT '影响幅度',
  `critical_point` decimal(15,4) DEFAULT NULL COMMENT '临界点',
  `detailed_results` longtext COMMENT '详细结果数据(JSON)',
  `chart_data` longtext COMMENT '图表数据(JSON)',
  `confidence_lower` decimal(15,4) DEFAULT NULL COMMENT '置信区间下限',
  `confidence_upper` decimal(15,4) DEFAULT NULL COMMENT '置信区间上限',
  `standard_deviation` decimal(10,6) DEFAULT NULL COMMENT '标准偏差',
  `coefficient_variation` decimal(10,6) DEFAULT NULL COMMENT '变异系数',
  `correlation_coefficient` decimal(5,4) DEFAULT NULL COMMENT '相关性系数',
  `r_squared` decimal(5,4) DEFAULT NULL COMMENT 'R平方值',
  `optimal_value` decimal(15,4) DEFAULT NULL COMMENT '最优值',
  `optimal_confidence` decimal(3,2) DEFAULT NULL COMMENT '最优值信心度',
  `risk_assessment` longtext COMMENT '风险评估(JSON)',
  `recommendations` longtext COMMENT '建议措施(JSON)',
  `sort_order` int DEFAULT '0' COMMENT '排序序号',
  `is_critical` tinyint(1) DEFAULT '0' COMMENT '是否为关键参数',
  `is_controllable` tinyint(1) DEFAULT '1' COMMENT '是否可控',
  `calculation_status` varchar(32) DEFAULT 'completed' COMMENT '计算状态',
  `calculated_at` datetime DEFAULT NULL COMMENT '计算时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_analysis_id` (`analysis_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_parameter_name` (`parameter_name`),
  KEY `idx_parameter_category` (`parameter_category`),
  KEY `idx_sensitivity_level` (`sensitivity_level`),
  KEY `idx_sort_order` (`sort_order`),
  KEY `idx_is_critical` (`is_critical`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='盈亏平衡敏感性分析表';

-- 4. 盈亏平衡预测表
DROP TABLE IF EXISTS `soo_breakeven_forecast`;
CREATE TABLE `soo_breakeven_forecast` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `forecast_id` varchar(64) NOT NULL COMMENT '预测ID',
  `analysis_id` varchar(64) NOT NULL COMMENT '关联分析ID',
  `tenant_id` varchar(32) NOT NULL DEFAULT 'default' COMMENT '租户ID',
  `forecast_name` varchar(200) NOT NULL COMMENT '预测名称',
  `forecast_type` varchar(32) DEFAULT NULL COMMENT '预测类型(short_term/medium_term/long_term)',
  `forecast_period` varchar(32) DEFAULT NULL COMMENT '预测期间',
  `forecast_start_date` datetime DEFAULT NULL COMMENT '预测开始时间',
  `forecast_end_date` datetime DEFAULT NULL COMMENT '预测结束时间',
  `forecast_frequency` varchar(32) DEFAULT 'monthly' COMMENT '预测频率(monthly/quarterly/yearly)',
  `model_type` varchar(64) DEFAULT 'linear_regression' COMMENT '预测模型类型',
  `model_parameters` longtext COMMENT '模型参数配置(JSON)',
  `historical_window` int DEFAULT '24' COMMENT '历史数据窗口(月)',
  `training_data` longtext COMMENT '训练数据集(JSON)',
  `validation_data` longtext COMMENT '验证数据集(JSON)',
  `forecast_results` longtext COMMENT '预测结果数据(JSON)',
  `accuracy_metrics` longtext COMMENT '预测准确性指标(JSON)',
  `overall_accuracy` decimal(5,4) DEFAULT NULL COMMENT '整体准确率',
  `mean_absolute_error` decimal(15,4) DEFAULT NULL COMMENT '平均绝对误差',
  `root_mean_square_error` decimal(15,4) DEFAULT NULL COMMENT '均方根误差',
  `mean_absolute_percentage_error` decimal(5,4) DEFAULT NULL COMMENT '平均绝对百分比误差',
  `confidence_level` decimal(3,2) DEFAULT '0.95' COMMENT '置信水平',
  `confidence_intervals` longtext COMMENT '置信区间数据(JSON)',
  `trend_analysis` longtext COMMENT '趋势分析(JSON)',
  `seasonal_factors` longtext COMMENT '季节性因子(JSON)',
  `cyclical_patterns` longtext COMMENT '周期性模式(JSON)',
  `external_factors` longtext COMMENT '外部因子影响(JSON)',
  `forecast_assumptions` longtext COMMENT '预测假设条件(JSON)',
  `risk_factors` longtext COMMENT '风险因子(JSON)',
  `scenario_comparison` longtext COMMENT '情景对比(JSON)',
  `sensitivity_parameters` longtext COMMENT '敏感性参数(JSON)',
  `key_alerts` longtext COMMENT '关键节点预警(JSON)',
  `quality_rating` varchar(32) DEFAULT 'good' COMMENT '预测质量评级',
  `reliability_score` decimal(3,2) DEFAULT NULL COMMENT '可信度评分',
  `model_diagnostics` longtext COMMENT '模型诊断信息(JSON)',
  `data_quality_metrics` longtext COMMENT '数据质量指标(JSON)',
  `update_frequency` varchar(32) DEFAULT 'weekly' COMMENT '更新频率',
  `last_updated` datetime DEFAULT NULL COMMENT '最后更新时间',
  `next_update` datetime DEFAULT NULL COMMENT '下次更新时间',
  `forecast_status` varchar(32) NOT NULL DEFAULT 'ready' COMMENT '预测状态',
  `auto_update` tinyint(1) DEFAULT '1' COMMENT '是否自动更新',
  `is_public` tinyint(1) DEFAULT '0' COMMENT '是否公开',
  `version` varchar(32) DEFAULT '1.0' COMMENT '版本号',
  `creator_id` bigint DEFAULT NULL COMMENT '创建人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_forecast_id_tenant` (`forecast_id`, `tenant_id`),
  KEY `idx_analysis_id` (`analysis_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_forecast_type` (`forecast_type`),
  KEY `idx_model_type` (`model_type`),
  KEY `idx_forecast_status` (`forecast_status`),
  KEY `idx_next_update` (`next_update`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='盈亏平衡预测表';

-- 5. 盈亏平衡配置表
DROP TABLE IF EXISTS `soo_breakeven_config`;
CREATE TABLE `soo_breakeven_config` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `config_key` varchar(100) NOT NULL COMMENT '配置项键',
  `config_name` varchar(200) NOT NULL COMMENT '配置项名称',
  `config_category` varchar(64) NOT NULL COMMENT '配置分类',
  `tenant_id` varchar(32) NOT NULL DEFAULT 'default' COMMENT '租户ID',
  `config_value` text COMMENT '配置值',
  `numeric_value` decimal(15,4) DEFAULT NULL COMMENT '数值类型配置值',
  `boolean_value` tinyint(1) DEFAULT NULL COMMENT '布尔类型配置值',
  `json_value` longtext COMMENT 'JSON配置内容',
  `description` text COMMENT '配置描述',
  `default_value` text COMMENT '默认值',
  `value_options` text COMMENT '值域/选项',
  `data_type` varchar(32) NOT NULL DEFAULT 'string' COMMENT '数据类型',
  `is_required` tinyint(1) DEFAULT '0' COMMENT '是否必填',
  `is_enabled` tinyint(1) DEFAULT '1' COMMENT '是否启用',
  `is_system` tinyint(1) DEFAULT '0' COMMENT '是否系统级配置',
  `is_editable` tinyint(1) DEFAULT '1' COMMENT '是否可编辑',
  `display_order` int DEFAULT '0' COMMENT '显示顺序',
  `validation_rules` text COMMENT '验证规则',
  `format_rules` text COMMENT '格式化规则',
  `dependencies` text COMMENT '依赖条件',
  `impact_scope` varchar(100) DEFAULT NULL COMMENT '影响范围',
  `min_value` decimal(15,4) DEFAULT NULL COMMENT '最小值',
  `max_value` decimal(15,4) DEFAULT NULL COMMENT '最大值',
  `step_value` decimal(15,4) DEFAULT NULL COMMENT '步长',
  `unit` varchar(32) DEFAULT NULL COMMENT '单位',
  `precision` int DEFAULT NULL COMMENT '精度',
  `remarks` text COMMENT '备注信息',
  `version` varchar(32) DEFAULT '1.0' COMMENT '版本号',
  `effective_date` datetime DEFAULT NULL COMMENT '生效时间',
  `expiry_date` datetime DEFAULT NULL COMMENT '失效时间',
  `creator_id` bigint DEFAULT NULL COMMENT '创建人ID',
  `modifier_id` bigint DEFAULT NULL COMMENT '最后修改人ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_config_key_tenant` (`config_key`, `tenant_id`),
  KEY `idx_config_category` (`config_category`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_is_enabled` (`is_enabled`),
  KEY `idx_is_system` (`is_system`),
  KEY `idx_display_order` (`display_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='盈亏平衡配置表';

-- 添加外键约束（可选，根据实际需要）
-- ALTER TABLE `soo_breakeven_scenarios` ADD CONSTRAINT `fk_scenarios_analysis` 
--   FOREIGN KEY (`analysis_id`) REFERENCES `soo_breakeven_analysis` (`analysis_id`) ON DELETE CASCADE;

-- ALTER TABLE `soo_breakeven_sensitivity` ADD CONSTRAINT `fk_sensitivity_analysis` 
--   FOREIGN KEY (`analysis_id`) REFERENCES `soo_breakeven_analysis` (`analysis_id`) ON DELETE CASCADE;

-- ALTER TABLE `soo_breakeven_forecast` ADD CONSTRAINT `fk_forecast_analysis` 
--   FOREIGN KEY (`analysis_id`) REFERENCES `soo_breakeven_analysis` (`analysis_id`) ON DELETE CASCADE;

-- 创建视图：分析概览
CREATE OR REPLACE VIEW `v_breakeven_analysis_overview` AS
SELECT 
    ba.analysis_id,
    ba.analysis_name,
    ba.analysis_type,
    ba.analysis_period,
    ba.tenant_id,
    ba.creator_name,
    ba.breakeven_point,
    ba.margin_safety_ratio,
    ba.reasonability_score,
    ba.status,
    ba.created_at,
    ba.last_recalculation,
    COUNT(bs.id) as scenario_count,
    COUNT(bse.id) as sensitivity_count,
    COUNT(bf.id) as forecast_count
FROM soo_breakeven_analysis ba
LEFT JOIN soo_breakeven_scenarios bs ON ba.analysis_id = bs.analysis_id AND bs.status = 'active'
LEFT JOIN soo_breakeven_sensitivity bse ON ba.analysis_id = bse.analysis_id
LEFT JOIN soo_breakeven_forecast bf ON ba.analysis_id = bf.analysis_id AND bf.forecast_status = 'ready'
WHERE ba.status = 'active'
GROUP BY ba.analysis_id, ba.analysis_name, ba.analysis_type, ba.analysis_period, 
         ba.tenant_id, ba.creator_name, ba.breakeven_point, ba.margin_safety_ratio, 
         ba.reasonability_score, ba.status, ba.created_at, ba.last_recalculation; 